# Generated by Django 5.2.15 on 2026-06-14 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integrationjob',
            name='endpoint',
        ),
        migrations.RemoveField(
            model_name='scannedfile',
            name='uploaded_by',
        ),
        migrations.DeleteModel(
            name='IntegrationEndpoint',
        ),
        migrations.DeleteModel(
            name='IntegrationJob',
        ),
        migrations.DeleteModel(
            name='ScannedFile',
        ),
    ]
