# Generated by Django 5.2.15 on 2026-06-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='is_clean',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='taskdependency',
            name='type',
            field=models.CharField(choices=[('FS', 'Finish→Start'), ('SS', 'Start→Start'), ('FF', 'Finish→Finish'), ('SF', 'Start→Finish')], default='FS', max_length=2),
        ),
    ]
