# Generated by Django 5.2.15 on 2026-07-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_add_task_comment_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='comment',
            name='number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('task', 'number')},
        ),
    ]
